from database import BaseModel
from database.models import Map, Player
from peewee import *

class PlayerStat(BaseModel):
    map_id = ForeignKeyField(Map, backref='player_stats')
    player_id = ForeignKeyField(Player, backref='stats')

    one_v_one_count = SmallIntegerField()
    one_v_one_wins = SmallIntegerField()
    one_v_two_count = SmallIntegerField()
    one_v_two_wins = SmallIntegerField()
    adr = FloatField()  # Average Damage per Round
    assists = SmallIntegerField()
    clutch_kills = SmallIntegerField()
    damage = IntegerField()
    deaths = SmallIntegerField()
    double_kills = SmallIntegerField()
    enemies_flashed = SmallIntegerField()
    enemies_flashed_per_round = FloatField()
    entry_count = SmallIntegerField()
    entry_wins = SmallIntegerField()
    first_kills = SmallIntegerField()
    flash_count = SmallIntegerField()
    flash_success_rate = FloatField()
    flash_successes = SmallIntegerField()
    flashes_per_round = FloatField()
    headshots = SmallIntegerField()
    headshot_percentage = SmallIntegerField()
    kd_ratio = FloatField()
    kr_ratio = FloatField()  # Kills per Round Ratio
    kills = SmallIntegerField()
    knife_kills = SmallIntegerField()
    mvps = SmallIntegerField()
    match_one_v_one_win_rate = FloatField()
    match_one_v_two_win_rate = FloatField()
    match_entry_rate = FloatField()
    match_entry_success_rate = FloatField()
    penta_kills = SmallIntegerField()
    pistol_kills = SmallIntegerField()
    quadro_kills = SmallIntegerField()
    sniper_kill_rate = FloatField()
    sniper_kill_rate_per_round = FloatField()
    sniper_kills = SmallIntegerField()
    triple_kills = SmallIntegerField()
    utility_count = SmallIntegerField()
    utility_damage = IntegerField()
    utility_damage_success_rate = FloatField()
    utility_damage_per_round = FloatField()
    utility_enemies = SmallIntegerField()
    utility_success_rate = FloatField()
    utility_successes = SmallIntegerField()
    utility_usage_per_round = FloatField()
    zeus_kills = SmallIntegerField()