from .nationals import nationals_table, reduction_table
from .get_group_rankings import get_group_rankings, get_number_of_groups, get_number_of_divisions
from .nationals_placements import get_national_placements
